name: Backend workflow

on:
  push:
    branches:
      - master
      - main

jobs:
  code-quality-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"
          cache: false

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.61.0

      - name: Go test
        run: go test -v ./...

  version-tag:
    runs-on: ubuntu-latest
    needs: code-quality-check
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Push version tag
        uses: falokut/version-tag-action@v1
        with:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docker-image:
    runs-on: ubuntu-latest
    environment: Default
    needs: code-quality-check
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Push Docker Image
        uses: falokut/docker-image-action@v1
        with:
          image_name: ${{ github.event.repository.name }}
          registry_username: ${{ secrets.DOCKER_USERNAME }}
          registry_password: ${{ secrets.DOCKER_PASSWORD }}
